services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'danil'
      POSTGRES_DB: 'practice'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U danil -d practice"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  init_bd:
    build:
      context: ./init_db
      dockerfile: Dockerfile
    environment:
      DB_NAME: practice
      DB_USER: danil
      DB_PASSWORD: 12345
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy

  telegram_bot:
    build: 
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_NAME: practice
      DB_USER: danil
      DB_PASSWORD: 12345
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: